package requests

import "context"

// GetPagination is the request that will be generated by the calendar adapter and send to the
// storage object to be consumed This contains the data from the query params PLUS the userID
// that will be taken from the gin context
type GetPagination struct {
	Ctx    context.Context
	UserID string
	Sdate  string `form:"sdate"`
	Desc   bool   `form:"desc"`
	Limit  int    `form:"limit"`
	Offset int    `form:"offset"`
}

// NewGetPagination is the constructor function for the GetPagination struct
func NewGetPagination(userID string) *GetPagination {
	return &GetPagination{
		Ctx:    context.Background(),
		UserID: userID,
	}
}
